title: GSCN workshop 2024
author: Sara Jimenez
execute:
    execute_notebooks: "off"

repository:
    url: https://github.com/sarajimenez/GSCN_workshop_2024
    provider: "github"
html:
    use_repository_button: true
