title: GSCN workshop 2024
author: Sara Jimenez
execute:
    execute_notebooks: "off"

repository:
    url: https://sarajimenez.github.io/GSCN_workshop_2024/
repository_provider: "github"
html:
    use_repository_button: true
